services:
  rpweaveapi:
    image: cooldruid12/rpweave.api:edge
    user: root
    container_name: rpweaveapi
    environment:
      - Authentication__TokenSecret=${AuthenticationTokenSecret}                  # secret value used for access token generation
      - Authentication__RefreshTokenSecret=${AuthenticationRefreshTokenSecret}    # secret value used for refresh token generation
      - PublicBaseUrl=${ApiPublicBaseUrl}                                         # base url of the api
      - MongoServerName=${MongoServerName}                                        # container name of your mongo instance
      - QdrantServerName=${QdrantServerName}                                      # container name of your qdrant instance
      - OllamaServerName=${OllamaServerName}                                      # container name of your ollama instance
      - OllamaReasoningModelName=${OllamaReasoningModelName}                      # your preferred reasoning model
      - OllamaEmbeddingsModelName=${OllamaEmbeddingsModelName}                    # your preferred embeddings model
    volumes:
      - uploads:/srv/rpweave/uploads
    ports:
      - "5000:8080"

  rpweaveui:
    image: cooldruid12/rpweave.ui:edge
    container_name: rpweaveui
    environment:
      - RpWeaveApiBaseUrl=${RpWeaveApiBaseUrl}                                    # url of the api to connect to, usually "http://<api_container_name>:8080"
    ports:
      - "5010:80"

  mongo:
    image: mongo
    container_name: mongo.demo
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: ${MongoServerName}
    depends_on:
      - mongo

  ollama:
    image: ollama/ollama
    container_name: ollama.demo
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant.demo
    ports:
      - 6333:6333

volumes:
  mongodbdata:
  ollama:
  uploads: