name: rpweave dev

services:
  rpweave.server.api:
    image: rpweave.server.api
    user: root
    build:
      context: ./RpWeave.Server
      dockerfile: ./Dockerfile
    environment:
      - Authentication__TokenSecret=thisisthesecretforgeneratingakey(mustbeatleast32bitlong)
      - Authentication__RefreshTokenSecret=thisisthesecretforgeneratingakey(mustbeatleast32bitlong)
      - PublicBaseUrl=http://localhost:8080
      - MongoServerName=mongo
      - QdrantServerName=qdrant
      - OllamaServerName=ollama
      - OllamaReasoningModelName=qwen3:8b
      - OllamaEmbeddingsModelName=bge-m3:latest
    volumes:
      - ./testResults:/home/test
      - uploads:/srv/rpweave/uploads
    ports:
      - "5000:8080"

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_DEBUG=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # alternatively, use `count: all` for all GPUs
              capabilities: [gpu]

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - 6333:6333
    volumes:
      - qdrant:/qdrant/storage

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - 5678:5678
    environment:
      - GENERIC_TIMEZONE=Europe/Amsterdam
      - TZ=Europe/Amsterdam
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
    volumes:
      - n8ndata:/home/node/.n8n

volumes:
  mongodbdata:
  ollama:
  uploads:
  client:
  n8ndata:
  qdrant: